run: 2125_main_queue.o 2125_queue.o
	gcc -o run 2125_main_queue.o 2125_queue.o
2125_main_queue.o: 2125_main_queue.c 2125_queue.h
	gcc -c 2125_main_queue.c
2125_queue.o: 2125_queue.c 2125_queue.h
	gcc -c 2125_queue.c